name: CI

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3.5.0

      - run: |
          git config --local core.autocrlf true
          git config --local user.name "Microsoft GitHub User"
          git config --local user.email msftgits@microsoft.com

      - run: |
          cd .\tools\v1.0
          .\launch.ps1 > ..\..\defconfig

      - run: |
          git add defconfig
          git commit --message "Update to the latest Microsoft Teams builds"
          git push

      - run: |
          cd .\tools\v1.0
          .\x64.ps1 > ..\..\defconfigx64

      - run: |
          git add defconfigx64
          git commit --message "Update to the latest Microsoft Teams builds"
          git push

      - run: |
          cd .\tools\v1.0
          .\x86.ps1 > ..\..\defconfigx86

      - run: |
          git add defconfigx86
          git commit --message "Update to the latest Microsoft Teams builds"
          git push

      - run: |
          git add .github\ci\v1.0
          git commit --message "Update to the latest CI files"
          git push

      - run: |
          cd ".\tools\v1.0 + v2.0"
          .\launch.ps1 > ..\..\defconfig2

      - run: |
          git add defconfig2
          git commit --message "Update to the latest Microsoft Teams builds"
          git push
